# config.yaml
bounce_alg_node:
  ros__parameters:
    #velocity
    linear_vel:         0.2
    angular_vel:        0.3
    #ground filtration
    ground_elevation:   0.15
    ground_tolerance:   0.2
    ground_threshold:    0.4
    #obstacle avoidance
    above_filtration:   0.2
    slow_threshold:     2.0
    stop_threshold:     1.5
    obstacle_zone_y:    1.2
    #transform point cloud from LiDAR to robot
    translation:          [0.15, 0.0, -0.262]
    #simulation bool
    simulation:         false
