# config.yaml
bounce_alg_node:
  ros__parameters:
    #velocity
    linear_vel:         0.2
    angular_vel:        0.4
    #ground filtration
    ground_elevation:   0.1
    ground_tolerance:   0.1
    ground_treshold:    0.07
    #obstacle avoidance
    above_filtration:   0.2
    slow_threshold:     1.2
    stop_threshold:     2.5
    obstacle_zone_y:    2.0
    #transform point cloud from LiDAR to robot
    translation:          [0.15, 0.0, -0.262]
    #simulation bool
    simulation:         false
